export const personalInfo = {
  name: " Syam Prasad Reddydy",
  tagline: "Senior AI Engineer",
  shortName: "Syam Reddy",
  headline: "Building Intelligent Systems That Scale",
  subheadline:
    "Transforming complex AI research into production-ready products — from LLM pipelines and autonomous agents to intelligent APIs that handle millions of requests.",
  email: "syamreddypenumallu@gmail.com",
  github: "https://github.com/syamreddy",
  linkedin: "https://linkedin.com/in/syamprasad",
  location: "India",
  available: true,
  roles: [
    "Senior AI Engineer",
    "Backend Systems Engineer",
    "AI Agent Builder",
    "Software Devlopement Engineer-1",
  ],
};

export const stats = [
  { label: "Years of Experience", value: 3, suffix: "+" },
  { label: "AI Projects Shipped", value: 20, suffix: "+" },
  { label: "LLM Applications Built", value: 12, suffix: "+" },
  { label: "Uptime SLA Maintained", value: 99.9, suffix: "%" },
];

export const skills = {
  "AI / ML": [
    { name: "Python", level: 95 },
    { name: "LangChain", level: 92 },
    { name: "OpenAI API", level: 95 },
    { name: "LlamaIndex", level: 88 },
    { name: "Hugging Face", level: 85 },
    { name: "PyTorch", level: 78 },
    { name: "RAG Systems", level: 92 },
    { name: "Vector DBs", level: 88 },
    { name: "Prompt Engineering", level: 95 },
    { name: "Fine-tuning LLMs", level: 80 },
    { name: "CrewAI / AutoGen", level: 85 },
    { name: "Embeddings", level: 90 },
  ],
  Backend: [
    { name: "FastAPI", level: 92 },
    { name: "Node.js", level: 85 },
    { name: "PostgreSQL", level: 88 },
    { name: "Redis", level: 85 },
    { name: "MongoDB", level: 82 },
    { name: "GraphQL", level: 78 },
    { name: "REST APIs", level: 95 },
    { name: "Celery / Workers", level: 82 },
    { name: "Websockets", level: 80 },
    { name: "Microservices", level: 85 },
    { name: "gRPC", level: 72 },
    { name: "Message Queues", level: 82 },
  ],
  Frontend: [
    { name: "React.js", level: 88 },
    { name: "Next.js", level: 85 },
    { name: "TypeScript", level: 82 },
    { name: "Tailwind CSS", level: 90 },
    { name: "Framer Motion", level: 82 },
    { name: "Three.js", level: 70 },
    { name: "Zustand", level: 78 },
    { name: "Shadcn UI", level: 85 },
  ],
  "DevOps / Tools": [
    { name: "Docker", level: 88 },
    { name: "AWS", level: 82 },
    { name: "GCP", level: 78 },
    { name: "Kubernetes", level: 72 },
    { name: "CI/CD", level: 85 },
    { name: "GitHub Actions", level: 88 },
    { name: "Terraform", level: 70 },
    { name: "Pinecone", level: 88 },
    { name: "Weaviate", level: 82 },
    { name: "LangSmith", level: 85 },
  ],
};

export const projects = [
  {
    id: 1,
    title: "Autonomous AI Agent Platform",
    subtitle: "Multi-agent orchestration at production scale",
    description:
      "Built a multi-agent orchestration platform where specialized AI agents collaborate to complete complex, multi-step tasks. Agents can search the web, write code, analyze data, and communicate with each other — all with human-in-the-loop oversight.",
    problem: "Enterprises needed AI automation beyond single-prompt responses",
    solution: "Multi-agent architecture with task decomposition and orchestration",
    impact: "Reduced manual workflow time by 70% for 500+ enterprise users",
    tech: ["Python", "LangChain", "CrewAI", "FastAPI", "Redis", "PostgreSQL", "Docker"],
    color: "from-indigo-500/20 to-violet-500/20",
    accent: "#6366f1",
    github: "https://github.com/syamreddy",
    demo: "#",
    featured: true,
    metrics: ["70% time saved", "500+ users", "99.9% uptime"],
  },
  {
    id: 2,
    title: "Intelligent RAG Document Engine",
    subtitle: "Semantic search over 10M+ enterprise documents",
    description:
      "Engineered a production-grade Retrieval-Augmented Generation system that enables natural language querying over massive document corpora. Features hybrid search, re-ranking, and citation-aware responses with hallucination detection.",
    problem: "Finding insights in millions of documents was impossible at scale",
    solution: "Hybrid vector + keyword search with LLM-powered synthesis",
    impact: "Query latency under 800ms on 10M+ document corpus",
    tech: ["Python", "LlamaIndex", "Pinecone", "OpenAI", "FastAPI", "React"],
    color: "from-violet-500/20 to-cyan-500/20",
    accent: "#8b5cf6",
    github: "https://github.com/syamreddy",
    demo: "#",
    featured: true,
    metrics: ["10M+ docs", "<800ms p99", "94% accuracy"],
  },
  {
    id: 3,
    title: "AI-Powered API Gateway",
    subtitle: "Smart routing, caching & rate limiting with ML",
    description:
      "Designed and shipped a next-generation API gateway that uses ML models for intelligent request routing, semantic response caching, and anomaly detection. Learns traffic patterns to auto-scale and prevent abuse.",
    problem: "Traditional API gateways wasted compute on duplicate LLM calls",
    solution: "Semantic caching layer + ML-based routing reduced costs by 60%",
    impact: "Saved $40K/month in LLM API costs for a mid-size SaaS",
    tech: ["Go", "Python", "Redis", "Kubernetes", "Prometheus", "Grafana"],
    color: "from-cyan-500/20 to-indigo-500/20",
    accent: "#06b6d4",
    github: "https://github.com/syamreddy",
    demo: "#",
    featured: true,
    metrics: ["60% cost reduction", "$40K/mo saved", "2M req/day"],
  },
  {
    id: 4,
    title: "Real-Time AI Analytics Dashboard",
    subtitle: "Streaming ML insights at millisecond latency",
    description:
      "Full-stack analytics platform with real-time ML inference on streaming data. Features anomaly detection, predictive forecasting, and natural language report generation — all updating live as data flows in.",
    problem: "Business teams needed instant ML insights without engineering bottlenecks",
    solution: "Streaming ML pipeline with WebSocket frontend and NL report generation",
    impact: "Teams reduced time-to-insight from hours to seconds",
    tech: ["Python", "Kafka", "FastAPI", "WebSockets", "Next.js", "D3.js", "OpenAI"],
    color: "from-indigo-500/20 to-pink-500/20",
    accent: "#a855f7",
    github: "https://github.com/syamreddy",
    demo: "#",
    featured: false,
    metrics: ["<100ms latency", "1M events/day", "10 sec reports"],
  },
  {
    id: 5,
    title: "LLM Fine-Tuning Infrastructure",
    subtitle: "Custom model training pipeline for domain tasks",
    description:
      "Built end-to-end fine-tuning infrastructure for training domain-specific LLMs. Includes dataset curation, PEFT/LoRA training, evaluation harness, and one-click deployment to inference endpoints.",
    problem: "Generic LLMs underperform on specialized enterprise domains",
    solution: "Automated LoRA fine-tuning pipeline with quality evaluation gates",
    impact: "Domain accuracy improved from 62% → 89% vs GPT-4",
    tech: ["Python", "PyTorch", "PEFT", "Hugging Face", "AWS SageMaker", "MLflow"],
    color: "from-pink-500/20 to-violet-500/20",
    accent: "#ec4899",
    github: "https://github.com/syamreddy",
    demo: "#",
    featured: false,
    metrics: ["89% domain accuracy", "+27pts vs GPT-4", "2hr train time"],
  },
];

export const experience = [
  {
    id: 1,
    role: "Senior AI Engineer",
    company: "Beacon.li",
    type: "Full-time",
    duration: "2024 — Present",
    location: "Remote",
    logo: "B",
    accent: "#6366f1",
    description:
      "Leading AI product development — architecting LLM-powered features, multi-agent systems, and intelligent backend infrastructure that powers thousands of daily active users.",
    achievements: [
      "Architected the company's core AI agent platform, enabling autonomous multi-step task execution with 99.9% reliability",
      "Built RAG pipeline serving 10M+ document corpus with sub-800ms p99 query latency",
      "Reduced LLM API costs by 60% through semantic caching and intelligent request batching",
      "Led end-to-end delivery of 5 AI-powered features that drove 40% improvement in user retention",
      "Established AI engineering best practices, code review standards, and MLOps workflows for the team",
    ],
    tech: ["Python", "LangChain", "FastAPI", "PostgreSQL", "Redis", "AWS", "Docker"],
  },
  {
    id: 2,
    role: "Software Development Engineer I",
    company: "Tech Startup",
    type: "Full-time",
    duration: "2023 — 2024",
    location: "Hybrid",
    logo: "T",
    accent: "#8b5cf6",
    description:
      "Joined as an early-career engineer and quickly took ownership of backend services and API development. Shipped critical features that scaled from zero to production.",
    achievements: [
      "Designed and implemented RESTful API services handling 500K+ daily requests with 99.5% uptime",
      "Reduced database query times by 65% through indexing strategy and query optimization",
      "Built an automated data pipeline processing 1M+ records daily, replacing a 3-hour manual process",
      "Mentored 2 junior developers and authored internal engineering documentation adopted company-wide",
      "Integrated first LLM-powered feature into the product, sparking the team's transition to AI-first development",
    ],
    tech: ["Node.js", "PostgreSQL", "Redis", "Docker", "AWS", "React"],
  },
  {
    id: 3,
    role: "B.Tech in ECE",
    company: "University",
    type: "Education",
    duration: "2019 — 2023",
    location: "On-campus",
    logo: "U",
    accent: "#06b6d4",
    description:
      "Electronics and Communication Engineering — the foundation that shaped my analytical thinking and systems-level perspective. Where hardware intuition met software ambition.",
    achievements: [
      "Graduated with distinction; final-year project on ML-based signal classification achieved 94% accuracy",
      "Built IoT + ML project that won Best Innovation Award at the university tech fest",
      "Led the coding club, organizing hackathons that attracted 500+ participants",
      "Self-taught Python, ML fundamentals, and web development during academic years",
    ],
    tech: ["Python", "MATLAB", "C++", "TensorFlow", "IoT", "Signal Processing"],
  },
];

export const aiWork = [
  {
    id: 1,
    title: "Multi-Agent Systems",
    icon: "🤖",
    description:
      "Designing autonomous agent networks where specialized AI models collaborate, delegate subtasks, and self-correct — enabling end-to-end automation of complex workflows.",
    capabilities: [
      "Task decomposition & orchestration",
      "Agent-to-agent communication",
      "Tool use & function calling",
      "Human-in-the-loop checkpoints",
    ],
    accent: "#6366f1",
    gradient: "from-indigo-600 to-violet-600",
  },
  {
    id: 2,
    title: "RAG & Knowledge Systems",
    icon: "🧠",
    description:
      "Building production-grade RAG pipelines that make LLMs grounded, accurate, and explainable — from chunking strategies to hybrid retrieval and re-ranking.",
    capabilities: [
      "Hybrid vector + keyword search",
      "Multi-hop reasoning chains",
      "Hallucination detection & mitigation",
      "Citation-aware response synthesis",
    ],
    accent: "#8b5cf6",
    gradient: "from-violet-600 to-purple-600",
  },
  {
    id: 3,
    title: "LLM Fine-Tuning",
    icon: "⚡",
    description:
      "Training domain-specific models using PEFT/LoRA techniques that outperform GPT-4 on narrow tasks — at a fraction of the inference cost.",
    capabilities: [
      "LoRA / QLoRA fine-tuning",
      "Dataset curation & synthesis",
      "RLHF-style preference optimization",
      "Evaluation harness design",
    ],
    accent: "#06b6d4",
    gradient: "from-cyan-600 to-teal-600",
  },
  {
    id: 4,
    title: "AI Infrastructure & MLOps",
    icon: "🏗️",
    description:
      "Building the pipes that make AI reliable in production — observability, semantic caching, versioning, rollback, and cost optimization at scale.",
    capabilities: [
      "LLMOps & prompt versioning",
      "Semantic response caching",
      "Token cost optimization",
      "A/B testing for AI features",
    ],
    accent: "#10b981",
    gradient: "from-emerald-600 to-teal-600",
  },
];

export const achievements = [
  {
    id: 1,
    title: "Claude Foundation Certified Architect",
    org: "Anthropic",
    year: "2026",
    description: "Earned the Claude Foundation Certified Architect certification, demonstrating expertise in designing and building AI-powered applications using Claude.",
    icon: "🏆",
  },
  {
    id: 2,
    title: "60% Cost Reduction",
    org: "Production Achievement",
    year: "2024",
    description: "Cut LLM API costs by 60% through semantic caching",
    icon: "💰",
  },
  {
    id: 3,
    title: "Top 5% GitHub",
    org: "Open Source",
    year: "2024",
    description: "Contributed to 3 major AI open-source repositories",
    icon: "⭐",
  },
  {
    id: 4,
    title: "0→Production in 6 Weeks",
    org: "Startup Milestone",
    year: "2024",
    description: "Shipped the core AI platform from scratch to production",
    icon: "🚀",
  },
];

export const navLinks = [
  { label: "About", href: "#about" },
  { label: "Skills", href: "#skills" },
  { label: "Projects", href: "#projects" },
  { label: "Experience", href: "#experience" },
  { label: "AI Work", href: "#ai-work" },
  { label: "Contact", href: "#contact" },
];
